extends RefCounted
class_name GDScriptGameKit

@warning_ignore_start("unsafe_method_access", "unsafe_property_access", "inferred_declaration")

var _game_kit: RefCounted

signal achievement_reported(achievement: Dictionary)
signal achievements_loaded(achievements: Array)
signal achievement_names_loaded(names: Array)


func _init() -> void:
	if not OS.get_name() == "iOS":
		return # only for iOS
	if not ClassDB.class_exists("GodotGameKit"):
		return # Class should have been generated by addon

	# start GameCenter initialization
	_game_kit = ClassDB.instantiate("GodotGameKit")

	# signal connections
	_game_kit.game_center_initialized.connect(_on_gc_initialized)
	_game_kit.achievement_reported.connect(_on_achievement_reported)
	_game_kit.achievements_loaded.connect(_on_achievements_loaded)
	_game_kit.achievement_names_loaded.connect(_on_achievement_names_loaded)

	_game_kit.initialize_game_center()


func _on_gc_initialized(initialized: bool, error: String) -> void:
	if error.is_empty():
		print("Game Center initialized:", initialized)
	else:
		print("Game Center init failed:", error)

	print("is_authenticated():", _game_kit.is_authenticated())


# --- Achievements ---

func load_achievement_names() -> void:
	if not _game_kit:
		push_warning("GameKit not initialized, cannot load achievement names.")
		return
	_game_kit.load_achievement_names()

func report_achievement(achievement_id: String, percent_complete: float = 100.0) -> void:
	if not _game_kit:
		push_warning("GameKit not initialized, cannot report achievement.")
		return
	_game_kit.report_achievement(achievement_id, percent_complete)

func load_achievements() -> void:
	if not _game_kit:
		push_warning("GameKit not initialized, cannot load achievements.")
		return
	_game_kit.load_achievements()

func _on_achievement_reported(achievement: Dictionary) -> void:
	# achievement is a Dictionary :
	# {
	#   "identifier": String,
	#   "percent_complete": float,
	#   "completed": bool,
	#   "last_reported": float (unix time, optional),
	#   "error": String
	# }
	achievement_reported.emit(achievement)
	if achievement.has("error") and achievement["error"]=="":
		load_achievements()

# get a list of player achievement situation
func _on_achievements_loaded(achievements: Array) -> void:
	# achievements is an Array of the same dictionaries as above
	achievements_loaded.emit(achievements)

# get a list of all available achievements
func _on_achievement_names_loaded(names: Array) -> void:
	achievement_names_loaded.emit(names) 
